services:
  db:
    image: postgres:15-alpine
    container_name: stars_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "1111:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: stars_redis
    restart: always
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: stars_api
    restart: always
    command: uv run uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  celery_worker:
    build: .
    container_name: stars_celery_worker
    restart: always
    command: uv run celery -A app.celery_app worker --loglevel=info
    depends_on:
      - db
      - redis
    env_file:
      - .env

  celery_beat:
    build: .
    container_name: stars_celery_beat
    restart: always
    command: uv run celery -A app.celery_app beat --loglevel=info
    depends_on:
      - redis
    env_file:
      - .env

  bot:
    build: .
    container_name: stars_bot
    restart: always
    command: uv run python -m tg_bot.run_bot
    env_file:
      - .env
    depends_on:
      - db
      - redis

volumes:
  postgres_data: