"""add refund and topup enums

Revision ID: 1364d832c039
Revises: 0b50cc9c3b09
Create Date: 2026-02-27 18:35:02.617078

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1364d832c039'
down_revision: Union[str, Sequence[str], None] = '0b50cc9c3b09'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("COMMIT")
    op.execute("ALTER TYPE actiontype ADD VALUE IF NOT EXISTS 'order_refund'")
    op.execute("ALTER TYPE actiontype ADD VALUE IF NOT EXISTS 'admin_topup'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
