"""empty message

Revision ID: 25b6d2f3b791
Revises: e8b228bd03f9
Create Date: 2026-02-21 13:26:55.688837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25b6d2f3b791'
down_revision: Union[str, Sequence[str], None] = 'e8b228bd03f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('action_type', sa.VARCHAR(length=30), nullable=False))
    op.drop_column('tasks', 'name')
    op.drop_column('tasks', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('description', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('orders', 'action_type')
    # ### end Alembic commands ###
