"""add new column refferal_earned to user table

Revision ID: 30febb0c8aed
Revises: 299ecaf1e0cc
Create Date: 2026-03-03 02:23:08.529962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30febb0c8aed'
down_revision: Union[str, Sequence[str], None] = '299ecaf1e0cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referral_earned', sa.BIGINT(), nullable=False, server_default=sa.text('0')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'referral_earned')
    # ### end Alembic commands ###
