"""user column add strike, is_banned

Revision ID: 37abb78d65ed
Revises: b11409b321a8
Create Date: 2026-02-27 14:36:32.232924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37abb78d65ed'
down_revision: Union[str, Sequence[str], None] = 'b11409b321a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('strikes', sa.BIGINT(), nullable=False))
    op.add_column('users', sa.Column('is_banned', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_banned')
    op.drop_column('users', 'strikes')
    # ### end Alembic commands ###
