"""empty message

Revision ID: 98ad0b898a3a
Revises: 25b6d2f3b791
Create Date: 2026-02-21 14:47:05.045844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '98ad0b898a3a'
down_revision: Union[str, Sequence[str], None] = '25b6d2f3b791'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_completions', sa.Column('completed_at', sa.TIMESTAMP(), nullable=False))
    op.drop_column('task_completions', 'complited_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_completions', sa.Column('complited_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('task_completions', 'completed_at')
    # ### end Alembic commands ###
