"""update table user_id

Revision ID: abdc4d6cc166
Revises: d75afad546d7
Create Date: 2026-02-25 20:47:50.705479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abdc4d6cc166'
down_revision: Union[str, Sequence[str], None] = 'd75afad546d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pending_payments', sa.Column('user_id', sa.BIGINT(), nullable=False))
    op.create_foreign_key(None, 'pending_payments', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pending_payments', type_='foreignkey')
    op.drop_column('pending_payments', 'user_id')
    # ### end Alembic commands ###
