"""empty message

Revision ID: c0d526b8b18d
Revises: 98ad0b898a3a
Create Date: 2026-02-21 21:04:29.889635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0d526b8b18d'
down_revision: Union[str, Sequence[str], None] = '98ad0b898a3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('subs_quantity', sa.BIGINT(), nullable=False))
    op.drop_column('orders', 'subs_ammount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('subs_ammount', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_column('orders', 'subs_quantity')
    # ### end Alembic commands ###
