"""Create Tasks, Tasks_completion, Orders | Tables

Revision ID: df82021efd82
Revises: 1891f9f150a9
Create Date: 2026-02-20 17:47:47.714648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df82021efd82'
down_revision: Union[str, Sequence[str], None] = '1891f9f150a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=True), nullable=False),
    sa.Column('creator_id', sa.BIGINT(), nullable=False),
    sa.Column('subs_ammount', sa.BIGINT(), nullable=False),
    sa.Column('reward_for_sub', sa.DECIMAL(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tasks',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=True), nullable=False),
    sa.Column('order_id', sa.BIGINT(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('description', sa.VARCHAR(length=100), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('task_completions',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=True), nullable=False),
    sa.Column('task_id', sa.BIGINT(), nullable=False),
    sa.Column('user_complete', sa.BIGINT(), nullable=False),
    sa.Column('complited_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ),
    sa.ForeignKeyConstraint(['user_complete'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('task_id', 'user_complete', name='idx_uniq_user_task')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_completions')
    op.drop_table('tasks')
    op.drop_table('orders')
    # ### end Alembic commands ###
