"""update ActionType in transaction_log

Revision ID: 0b50cc9c3b09
Revises: d9d55fb3711a
Create Date: 2026-02-27 17:30:21.238981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b50cc9c3b09'
down_revision: Union[str, Sequence[str], None] = 'd9d55fb3711a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("COMMIT") 
    op.execute("ALTER TYPE actiontype ADD VALUE 'admin_emission'")
    op.execute("ALTER TYPE actiontype ADD VALUE 'withdraw_approved'")
    op.execute("ALTER TYPE actiontype ADD VALUE 'withdraw_rejected'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
