"""Add transaction logs

Revision ID: 0dac8c41f901
Revises: 5c929a1478a5
Create Date: 2026-02-25 14:31:58.626079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0dac8c41f901'
down_revision: Union[str, Sequence[str], None] = '5c929a1478a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions_log',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=True), nullable=False),
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('amount', sa.DECIMAL(), nullable=False),
    sa.Column('wallet_type', sa.Enum('EARNED', 'DEPOSITED', name='wallettype'), nullable=False),
    sa.Column('action_type', sa.Enum('DEPOSIT', 'ORDER_CREATION', 'TASK_PAYMENT', 'SYSTEM_REVENUE', 'WITHDRAWAL', name='actiontype'), nullable=False),
    sa.Column('order_id', sa.BIGINT(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions_log')
    # ### end Alembic commands ###
