"""creata index for frozen balance

Revision ID: 299ecaf1e0cc
Revises: 801c0cdcef6f
Create Date: 2026-03-02 20:13:57.049090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '299ecaf1e0cc'
down_revision: Union[str, Sequence[str], None] = '801c0cdcef6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_task_completions_user_status', 'task_completions', ['user_complete', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_task_completions_user_status', table_name='task_completions')
    # ### end Alembic commands ###
