"""add new columns

Revision ID: 56ee6dc773d7
Revises: b5519fea6d00
Create Date: 2026-02-26 20:08:54.981697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

status_enum = postgresql.ENUM('FROZEN', 'COMPLETED', 'CANCELED', name='completionstatus')


# revision identifiers, used by Alembic.
revision: str = '56ee6dc773d7'
down_revision: Union[str, Sequence[str], None] = 'b5519fea6d00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    status_enum.create(op.get_bind())
    op.add_column('task_completions', sa.Column('stars_reward', sa.DECIMAL(precision=12, scale=2), nullable=False))
    op.add_column('task_completions', sa.Column('status', sa.Enum('FROZEN', 'COMPLETED', 'CANCELED', name='completionstatus'), nullable=False))
    op.add_column('task_completions', sa.Column('unlock_date', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_completions', 'unlock_date')
    op.drop_column('task_completions', 'status')
    op.drop_column('task_completions', 'stars_reward')
    op.drop(op.get_bind())
    # ### end Alembic commands ###
