"""add worker_pay column

Revision ID: 5c929a1478a5
Revises: 87b0c926c502
Create Date: 2026-02-24 15:29:17.652509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c929a1478a5'
down_revision: Union[str, Sequence[str], None] = '87b0c926c502'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('worker_pay', sa.DECIMAL(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'order_pay')
    # ### end Alembic commands ###
