"""fix enums in trans.log

Revision ID: 801c0cdcef6f
Revises: 1364d832c039
Create Date: 2026-02-28 13:59:53.889607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '801c0cdcef6f'
down_revision: Union[str, Sequence[str], None] = '1364d832c039'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("COMMIT")

    op.execute("ALTER TYPE actiontype ADD VALUE IF NOT EXISTS 'ADMIN_EMISSION'")
    op.execute("ALTER TYPE actiontype ADD VALUE IF NOT EXISTS 'ADMIN_TOPUP'")
    op.execute("ALTER TYPE actiontype ADD VALUE IF NOT EXISTS 'ORDER_REFUND'")
    op.execute("ALTER TYPE actiontype ADD VALUE IF NOT EXISTS 'WITHDRAW_APPROVED'")
    op.execute("ALTER TYPE actiontype ADD VALUE IF NOT EXISTS 'WITHDRAW_REJECTED'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
