"""empty message

Revision ID: 87b0c926c502
Revises: f9e09b90e837
Create Date: 2026-02-23 16:07:48.603264

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '87b0c926c502'
down_revision: Union[str, Sequence[str], None] = 'f9e09b90e837'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('description', sa.VARCHAR(length=250), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'description')
    # ### end Alembic commands ###
