"""create new table pending_payments

Revision ID: d75afad546d7
Revises: 35ad4877f882
Create Date: 2026-02-25 20:00:08.365410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd75afad546d7'
down_revision: Union[str, Sequence[str], None] = '35ad4877f882'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pending_payments',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=True), nullable=False),
    sa.Column('external_id', sa.String(), nullable=False),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('amount_stars', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('amount_fiat', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('CREATED', 'PAID', 'EXPIRED', name='paymentstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pending_payments_external_id'), 'pending_payments', ['external_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pending_payments_external_id'), table_name='pending_payments')
    op.drop_table('pending_payments')
    # ### end Alembic commands ###
