"""update orders table

Revision ID: d9d55fb3711a
Revises: 37abb78d65ed
Create Date: 2026-02-27 15:47:33.492805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9d55fb3711a'
down_revision: Union[str, Sequence[str], None] = '37abb78d65ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('current_subs', sa.BIGINT(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'current_subs')
    # ### end Alembic commands ###
